spring:
  application:
    name: reward-program
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:file:/rewardprogram
  h2:
    console:
      settings:
        trace: 'false'
        web-allow-others: 'false'
      path: /h2-console
      enabled: 'true'
  banner:
    image:
      location: classpath:banner.txt
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /rewardsprogram
  port: '8000'
